### ISSUE TITLE
Ahoka theme is too bright.

### ISSUE THREAD

**Issue by Penguin-Guru** [ahodesuka/dotfiles#3]
Let me first say that I know pretty much nothing about GTK so I may be overlooking something that should be obvious.

I would like to use your theme for ahoviewer. My system reads "~/.gtkrc-2.0". That seems to work, but at least two things (?) in ahoviewer are bright white-- the search bar's drop-down menu and the list of search terms with check-boxes in the bottom left corner. I haven't been able to figure out how to get ahoviewer to load gtk-3. The "bright white" seems pretty pure to me, so not #E9E6E6 or #CCCCCC. I tried changing those just to make sure but neither helped.

It may be that your theme just isn't compatible with my system for some reason but I don't know what kind of portability issue would cause those specific U.I. things. Maybe there are others I just haven't noticed but everything else is very dark so it's clearly working for the most part.

**Comment by ahodesuka** [comment]
My gtk2 theme requires the murrine gtk2 engine, without it things will not look correct.

**Comment by Penguin-Guru** [comment]
I did install murrine 0.98.2 from my distro's repo but I have no idea whether or not it's working. It's fine though. If you don't see anything wrong with the files here then it must be something on my system, feel free to close this issue. I'll just have to wait until I know enough about GTK to debug it. That is on my to-do list anyway...
